# Generated by Django 5.0.4 on 2024-04-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_all', models.CharField(max_length=10, verbose_name='Время')),
            ],
        ),
    ]
