# Generated by Django 5.0.4 on 2024-04-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_cust_recording_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страницы', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='recording_time',
            options={'verbose_name': 'Время записи клиентов', 'verbose_name_plural': 'Время записи клиентов'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ['time_all'], 'verbose_name': 'Время записи', 'verbose_name_plural': 'Время записи'},
        ),
        migrations.RenameField(
            model_name='recording_time',
            old_name='user',
            new_name='user_id',
        ),
    ]
