# Generated by Django 5.0.4 on 2024-04-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_page_options_alter_recording_time_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recording_time',
            old_name='user_id',
            new_name='user',
        ),
    ]
