# Generated by Django 5.0.4 on 2024-04-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_time_time_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='time_all',
            field=models.CharField(max_length=5, verbose_name='Время'),
        ),
    ]
