# Generated by Django 5.0.4 on 2024-05-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_time_time_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording_time',
            name='count',
            field=models.IntegerField(default=0, verbose_name='число записей'),
        ),
    ]
