# Generated by Django 5.0.4 on 2024-07-28 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_page_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страницу', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ['time_all'], 'verbose_name': 'Временной интервал клиентов', 'verbose_name_plural': 'Временной интервал клиентов'},
        ),
        migrations.AlterField(
            model_name='recording_time',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
